name: Pylint

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Clone other repositories
      run: |
        git clone https://github.com/Ravi0021/automate.git
        # Add more 'git clone' commands for additional repositories
    - name: Copy generic file to current repository
      run: cp automate/src/com/utils/restore_previous_versions_files.py generic/file.py
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=7 $(git ls-files '*.py')
